/*
 *  SuprSetr is Copyright 2010-2020 by Jeremy Brooks
 *
 *  This file is part of SuprSetr.
 *
 *   SuprSetr is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   SuprSetr is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with SuprSetr.  If not, see <http://www.gnu.org/licenses/>.
 */

package net.jeremybrooks.suprsetr;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import net.jeremybrooks.suprsetr.dao.LookupDAO;

import javax.swing.GroupLayout;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import java.awt.Container;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ResourceBundle;

/**
 * @author Jeremy Brooks
 */
public class LogWindow extends javax.swing.JFrame {

	private static final long serialVersionUID = 5655168820694116606L;

	/**
	 * Creates new form Log
	 */
	public LogWindow() {
		initComponents();
		String bounds;    // x, y, width, height

		try {
			bounds = LookupDAO.getValueForKey(SSConstants.LOOKUP_KEY_LOG_WINDOW_BOUNDS);
			if (bounds == null || bounds.isEmpty()) {
				bounds = "0 0 500 400";
			}
		} catch (Exception e) {
			bounds = "0 0 500 400";
		}

		String[] values = bounds.split(" ");
		try {
			setBounds(
					Integer.parseInt(values[0]),
					Integer.parseInt(values[1]),
					Integer.parseInt(values[2]),
					Integer.parseInt(values[3]));
		} catch (Exception e) {
			// ignore
		}
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		ResourceBundle bundle = ResourceBundle.getBundle("net.jeremybrooks.suprsetr.logwindow");
		jScrollPane1 = new JScrollPane();
		txtLog = new JTextArea();

		//======== this ========
		setTitle(bundle.getString("LogWindow.this.title"));
		setIconImage(new ImageIcon(getClass().getResource("/images/s16.png")).getImage());
		addWindowListener(new WindowAdapter() {
			@Override
			public void windowClosing(WindowEvent e) {
				formWindowClosing();
			}
		});
		Container contentPane = getContentPane();

		//======== jScrollPane1 ========
		{

			//---- txtLog ----
			txtLog.setColumns(20);
			txtLog.setEditable(false);
			txtLog.setRows(5);
			jScrollPane1.setViewportView(txtLog);
		}

		GroupLayout contentPaneLayout = new GroupLayout(contentPane);
		contentPane.setLayout(contentPaneLayout);
		contentPaneLayout.setHorizontalGroup(
			contentPaneLayout.createParallelGroup()
				.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
		);
		contentPaneLayout.setVerticalGroup(
			contentPaneLayout.createParallelGroup()
				.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
		);
		pack();
		setLocationRelativeTo(getOwner());
	}// </editor-fold>//GEN-END:initComponents

	private void formWindowClosing() {
		// save window size and position
		StringBuilder bounds = new StringBuilder();
		bounds.append(this.getX()).append(' ');
		bounds.append(this.getY()).append(' ');
		bounds.append(this.getWidth()).append(' ');
		bounds.append(this.getHeight());
		LookupDAO.setKeyAndValue(SSConstants.LOOKUP_KEY_LOG_WINDOW_BOUNDS, bounds.toString());
	}


	public static void addLogMessage(String message) {
		txtLog.append(message + "\n");
		txtLog.setCaretPosition(txtLog.getDocument().getLength());
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JScrollPane jScrollPane1;
	private static JTextArea txtLog;
	// End of variables declaration//GEN-END:variables

}
