/*
 * SuprSetr is Copyright 2010-2011 by Jeremy Brooks
 *
 * This file is part of SuprSetr.
 *
 *  SuprSetr is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  SuprSetr is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with SuprSetr.  If not, see <http://www.gnu.org/licenses/>.
*/

package net.jeremybrooks.suprsetr;

import java.awt.Frame;
import javax.swing.JOptionPane;
import net.jeremybrooks.suprsetr.workers.FlickrAuthenticatorWorker;
import org.apache.log4j.Logger;


/**
 * Display a dialog for Flickr authorization.
 *
 * @author jeremyb
 */
public class LoginDialog extends javax.swing.JDialog {

    /** Logging */
    private Logger logger = Logger.getLogger(LoginDialog.class);


    /** 
     * Creates new form LoginDialog.
     *
     * @param parent the parent frame.
     * @param modal display as modal.
     */
    public LoginDialog(Frame parent, boolean modal) {
	super(parent, modal);
	initComponents();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnAuthenticate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnPreferences = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Flickr Authentication Required");

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("NOTE: The Flickr library used by SuprSetr has changed. If you used a previous version of SuprSetr, the authorization token is now invalid, and you must authorize the application again. Sorry for the hassle.\n\nSuprSetr requires permission to access your Flickr account in order to work.\n\nClick the Authorize button to open a browser window to www.flickr.com. Once you have granted permission for SuprSetr to access your Flickr account, come back here.\n\nIf your network requires proxy access, click the Preferences button to set it up.");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        btnAuthenticate.setText("Authorize");
        btnAuthenticate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthenticateActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnPreferences.setText("Preferences");
        btnPreferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreferencesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnPreferences)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAuthenticate))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAuthenticate)
                    .addComponent(btnPreferences)
                    .addComponent(btnCancel)))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-419)/2, (screenSize.height-302)/2, 419, 302);
    }// </editor-fold>//GEN-END:initComponents


    /**
     * Do authentication.
     *
     * <p>This method will block the GUI, then use the FlickrAuthenticator
     * class to do the actual work of authentication.</p>
     *
     * @param evt button event.
     */
    private void btnAuthenticateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthenticateActionPerformed

	BlockerPanel blocker = new BlockerPanel(this, "Authenticating Flickr");
	setGlassPane(blocker);
	new FlickrAuthenticatorWorker(this, blocker).execute();

    }//GEN-LAST:event_btnAuthenticateActionPerformed


    /**
     * Allow user to cancel the operation.
     *
     * <p>Display a warning dialog that the program will exit if they continue.</p>
     *
     * @param evt button event.
     */
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
	int selection = JOptionPane.showConfirmDialog(this,
		"Canceling authentication will cause SuprSetr to exit.\n"
		+ "Are you sure?", "Cancel Authentication?",
		JOptionPane.YES_NO_OPTION,
		JOptionPane.QUESTION_MESSAGE);
	
	if (selection == JOptionPane.YES_OPTION) {
	    System.exit(0);
	}
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnPreferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreferencesActionPerformed
	Preferences prefs = new Preferences(null, true);
	prefs.setTabIndex(Preferences.PROXY_PANEL);
	prefs.setVisible(true);
    }//GEN-LAST:event_btnPreferencesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuthenticate;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPreferences;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
