package net.jeremybrooks.suprsetr;

import net.jeremybrooks.suprsetr.dao.LookupDAO;

/**
 *
 * @author jeremyb
 */
public class LogWindow extends javax.swing.JFrame {

    /** Creates new form Log */
    public LogWindow() {
        initComponents();
	String bounds = null;	// x, y, width, height

	try {
	    bounds = LookupDAO.getValueForKey(SSConstants.LOOKUP_KEY_LOG_WINDOW_BOUNDS);

	    if (bounds ==  null || bounds.isEmpty()) {
		bounds = "0 0 500 400";
	    }
	} catch (Exception e) {
	    bounds = "0 0 500 400";
	}

	String[] values = bounds.split(" ");

	try {
	    setBounds(
		    Integer.parseInt(values[0]),
		    Integer.parseInt(values[1]),
		    Integer.parseInt(values[2]),
		    Integer.parseInt(values[3]));
	} catch (Exception e) {
	    // ignore
	}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();

        setTitle("SuprSetr Activity");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        txtLog.setColumns(20);
        txtLog.setEditable(false);
        txtLog.setRows(5);
        jScrollPane1.setViewportView(txtLog);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
	// save window size and position
	StringBuilder bounds = new StringBuilder();
	bounds.append(this.getX()).append(' ');
	bounds.append(this.getY()).append(' ');
	bounds.append(this.getWidth()).append(' ');
	bounds.append(this.getHeight());
	LookupDAO.setKeyAndValue(SSConstants.LOOKUP_KEY_LOG_WINDOW_BOUNDS, bounds.toString());
    }//GEN-LAST:event_formWindowClosing


    public static void addLogMessage(String message) {
	txtLog.append(message + "\n");
	txtLog.setCaretPosition(txtLog.getDocument().getLength());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables

}
